language: objective-c
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
before_install:
  - brew update
  - brew install duti
  - sudo duti -s com.apple.TextEdit alfredworkflow all
install:
  - sudo pip install tox coveralls
  - sudo pip install pytest pytest_cov pytest_httpbin pytest_localserver
script:
  - tox -e $TOX_ENV
after_success:
  - cd tests
  - coveralls
