os: osx

osx_image: beta-xcode6.2

env:
  matrix:
    - VERSION=2.7.10 SOURCE=macpython
    - VERSION=2.6.9 SOURCE=macports

before_install:
  # - brew update
  - brew install duti
  - sudo duti -s com.apple.TextEdit alfredworkflow all

install:
  - git clone https://github.com/MacPython/terryfy
  - source terryfy/travis_tools.sh
  - get_python_environment $SOURCE $VERSION venv
  - extras/travis-install-deps.sh

script:
  - ./run-tests.sh

after_success:
  - cd tests
  - coveralls
